language: go
go: 
 - 1.5
 - 1.6
 - tip

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -coverprofile=coverage.txt ./

after_success:
  - bash <(curl -s https://codecov.io/bash) 




